- .babelrc
- package.json
- preact.config.js
- src/components/hello-world/index.js
- src/components/hello-world/style.scss
- src/components/hello-world/styled.js
- src/index.ejs
- yarn.lock
> Emotion support

- package.json
- preact.config.js
- src/helpers/reset-css.js
- src/helpers/styled-cache.js
- src/helpers/widget-wrapper.js
- src/index-with-global-styles.ejs
- src/index.ejs
- src/views/widget/index.js
- yarn.lock
> Add reset css to reset global syles and have a clean CSS state within the widget

- package.json
- yarn.lock
It seems we do not need sass and identity-obj-proxy
> Cleanup unused dependencies

- src/services/invoice.js
This class provides access to the invoice API and allows the client to get a new invoice and poll for the invoice status.
> Add initial InvoiceService to add and watch invoices

- src/containers/widget/index.js
- src/index.ejs
- src/views/welcome-screen/index.js
> Make welcome message configurable

- src/views/donate-screen/index.js
> Automatically trigger API for fetching invoice details when one of the selected amounts is selected

- src/views/donate-screen/index.js
> Clear the selected custom amount when the user manually enters amount

- package.json
- src/components/modal/styled.js
- src/components/title/styled.js
- src/utils/common-styles.js
- src/utils/helper.js
- src/views/donate-screen/index.js
- src/views/donate-screen/styled.js
- src/views/payment-screen/index.js
- src/views/payment-screen/styled.js
- src/views/welcome-screen/index.js
- yarn.lock
> Countdown timer & Progress bar for payments

- src/components/modal/styled.js
- src/components/title/styled.js
- src/utils/common-styles.js
- src/utils/reset-css.js
- src/views/payment-screen/index.js
- src/views/payment-screen/styled.js
- src/views/thankyou-screen/styled.js
> Fixes box-sizing layout issues in CSS

- src/containers/widget/index.js
- src/index.ejs
The token is different for each widget and needs to be configured when integrating
> Make backend token configurable

- src/components/button/index.js
- src/components/button/styled.js
- src/components/spinner/index.js
- src/components/spinner/styled.js
- src/containers/widget/index.js
- src/services/invoice.js
- src/utils/reset-css.js
- src/views/donate-screen/index.js
- src/views/payment-screen/styled.js
> Button loading & disabled states

- src/containers/widget/index.js
- src/index.ejs
- src/services/invoice.js
updated version of #55 
seems the widget is initialized on every screen change thus we use a global variable to store the interval id.
closes #55
> Stop watching the invoice when the modal is closed

- src/components/modal/index.js
- src/components/modal/styled.js
> Add background designs

- src/containers/widget/index.js
- src/views/payment-screen/index.js
> Show amount in satoshi next to normal currency

- src/containers/widget/index.js
If the welcomemessage is not set we can directly skip to the donation screen
@reznord can the initialization of props/state be unified? we now have code in the constructor, the componentDidMount and the setDefaults functions.
> Directly skip to the donation screen if the welcome message is blank

- src/index-with-global-styles.ejs
- src/index.ejs
- src/index.js
This removes the habitat reference from the HTML and makes the HTML
a bit easier
> Use class as habitat selector

- src/containers/widget/index.js
- src/index-with-global-styles.ejs
- src/index.ejs
- src/index.js
- src/views/donate-screen/index.js
This gives a bit more flexibility to the select fields
> Use object as payment options

- src/components/modal/styled.js
> Add z-index:-1 to make  the text selectable

- src/views/donate-screen/index.js
> Add check that amount is between 1 and 10000 cents

- src/components/modal/index.js
- src/components/title/index.js
- src/components/title/styled.js
- src/containers/widget/index.js
- src/index-with-global-styles.ejs
- src/index.ejs
this also renames the widgetTitle prop to title for easier use
> Add support for a title logo

- src/containers/widget/index.js
can't we access the entries on the state object here? this makes the code a bit shorter
> Shorter state access

- src/components/button/index.js
- src/components/modal/index.js
- src/components/title/index.js
- src/containers/widget/index.js
- src/index.ejs
- src/index.js
- src/utils/constants.js
- src/utils/styled-cache.js
- src/views/donate-screen/index.js
- src/views/payment-screen/index.js
This makes it easier to add custom CSS on specific elements.
> Add custom CSS classes to allow custom styling

- src/containers/widget/index.js
- src/index.ejs
This sets the state object in the constructor and uses setState when
calling setDefaults
> Fix initial state

- src/containers/widget/index.js
- src/utils/widget-wrapper.js
the CSS will be scoped to the widget
> Add option to provide custom stylesheets

- src/components/modal/styled.js
- src/components/title/index.js
- src/containers/base-class/index.js
- src/containers/inline-widget/index.js
- src/containers/widget/index.js
- src/index.ejs
- src/index.js
- yarn.lock
> Inline widget
